---
- hosts: kube
  become: true

  tasks:

    - name: Check if server is in /etc/hosts
      shell: cat /etc/hosts
      register: etc_hosts

    - name: Add lines to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item.ip }} {{ item.name }} {{ item.alt }}"
      with_items:
        - { name: rpi1.homelab.local, ip: 192.168.10.15, alt: rpi1}
        - { name: rpi2.homelab.local, ip: 192.168.10.16, alt: rpi2 }
      when: '"rpi1.homelab.local" and "rpi2.homelab.local" not in etc_hosts.stdout'